# Hugging Face Configuration
hf_token: "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"  

# Repository IDs (Format: username/repo-name)
checkpoint_repo_id: "gowthamgoli/LLM_training_checkpoints"
dataset_repo_id: "gowthamgoli/LLM_3B_tokens"

# Repository Types
checkpoint_repo_type: "model"
dataset_repo_type: "dataset"

# hf Paths
hf_checkpoint_dir: "checkpoints/checkpoint.pt"
hf_dataset_dir: "tokens"