tokenizer:
  name: meta-llama/Llama-2-7b-chat-hf
  use_fast: true
  eos_token: "</s>"

processing:
  text_column: text
  max_seq_len: 1024
  batch_size: 10000
  output_dir: /content/drive/MyDrive/LLM_Tokens/5B_tokens
  start_index: 0

files:
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset/resolve/main/clean_wikidump_0001.parquet
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset/resolve/main/clean_wikidump_0002.parquet
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset/resolve/main/clean_wikidump_0003.parquet
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset/resolve/main/clean_wikidump_0004.parquet
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset /resolve/main/clean_wikidump_0005.parquet
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset/resolve/main/clean_wikidump_0006.parquet
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset/resolve/main/clean_wikidump_0007.parquet
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset/resolve/main/clean_wikidump_0008.parquet
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset/resolve/main/clean_wikidump_0009.parquet
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset/resolve/main/clean_wikidump_0010.parquet
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset/resolve/main/clean_wikidump_0011.parquet
  - https://huggingface.co/datasets/gowthamgoli/wikimedia_dataset/resolve/main/clean_wikidump_0012.parquet